export const Films =[
    {id: 1, title: 'Minion: the rise of gru',img: 'assets/images/minion.jpg' , year: '2022',nation:'USA',
  detail: 'Minions: The Rise of Gru (original English title : Minions: The Rise of Gru ) is a2022 American computer-animated comedy film produced by Illumination and distributed by Universal Pictures . It is the sequel to the Minions spinoff (2015) and the fifth installment overall in the Moon Thieves series .',
clip:''},
    {id: 2, title: 'My hero academia',img: 'assets/images/myhero_academia.jpg', year: '2021',nation:'Japan',
    detail:'Hero Academy: Mission to Save the World is a 2021 Japanese animated superhero film, this is the third movie based on the popular manga series Superhero Academy by Kōhei Horikoshi.',
  clip:'https://www.youtube.com/embed/iaMLBWj6HjI'},
    {id: 3, title: 'Soul',img: 'assets/images/soul.jpg', year: '2020',nation:'USA',
    detail:'Magical Life is a 2020 American computer-animated comedy film produced by Walt Disney Pictures and Pixar Animation Studios, and distributed by Walt Disney Studios Motion Pictures.'},
    {id: 4, title: 'Thor: love and thunder',img: 'assets/images/thor.jpg', year: '2022',nation:'USA',
    detail:'Thor: Love and Thunder is an American superhero film based on the Marvel Comics character of the same name. This is the sequel to Thor: Ragnarok Apocalypse, which will also be the 29th film in the Marvel Cinematic Universe.'},
    {id: 5, title: 'Top gun: maverick',img: 'assets/images/top_gun.jpg', year: '2022',nation:'Ireland',
    detail:'Super Pilot Maverick is an American action drama film released in 2022. The film is directed by Joseph Kosinski, written by Ehren Kruger, Eric Warren Singer, Christopher McQuarrie, and the plot is built. created by Peter Craig and Justin Marks.'},
    {id: 6, title: 'Demon slayer',img: 'assets/images/demon_slayer.jpg', year: '2022',nation:'Japan',
    detail:'Demon Slayer, also known by its original name Kimetsu no Yaiba is a Japanese manga series written and illustrated by Gotōge Koyoharu. The story follows teenager Kamado Tanjirōs journey to become a demon slayer after his family was murdered by a demon and his sister Nezuko was turned into a demon.'},
    {id: 7, title: 'Dotor strange',img: 'assets/images/dotor_strange.jpg', year: '2022',nation:'USA',
    detail:'The Ultimate Wizard in the Chaos Multiverse is an American superhero film due out in 2022, based on the Marvel Comics character Doctor Strange.'},
    {id: 8, title: 'Jurassic world : dominion',img: 'assets/images/jurra.jpg', year: '2022',nation:'Australia',
    detail:'Dinosaur World: Territories is a 2022 American science fiction action film directed by Colin Trevorrow, who wrote the screenplay with Emily Carmichael, based on a story by Trevorrow and his screenwriter associates. you, Derek Connolly.'},
    {id: 9, title: 'Sang chi',img: 'assets/images/sang_chi.jpg', year: '2021',nation:'USA',
    detail:'Shang-Chi and the Legend of the Ten Luan is a 2021 American superhero film based on the Marvel Comics character Shang-Chi. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the 25th feature film in the Marvel Cinematic Universe.'},
  ];